### ISSUE TITLE
SwitchPathConfig buglets

### ISSUE THREAD

**Issue by DavidBrainard** [BrainardLab/BrainardLabToolbox#1]
After running SwitchPathConfig, certain Matlab stuff stops working.  For example, clicking on the line number link in an error printout causes a set of Undefined function messages.  It does actually then go to the line, but it is distracting.

See commend window copy/paste below.

Subscripted assignment dimension mismatch.

Error in plotOI>plotOTF (line 949)
        for ii=1:nWave, otfWave(:,ii) = fftshift(otf(1,:,ii)); end

Error in plotOI (line 563)
                udata = plotOTF(oi,'otf wavelength');

Error in t_opticsImageFormation (line 380)
cOTF = plotOI(oi,'otf wavelength');

Warning: Negative limits ignored 

> > close all
> > edit
> > Undefined function 'rmiml.getAll' for input arguments of type 'char'.

Undefined function 'rmiml.visibleInToolstrip' for input arguments of type 'char'.

Undefined function 'rmiml.visibleInToolstrip' for input arguments of type 'char'.

Undefined function 'rmiml.visibleInToolstrip' for input arguments of type 'char'.

**Comment by npcottaris** [comment]
After updating my Java Installation to Java 8 Update 45, this problem was eliminated.
SystemPreferences -> Java (all the way at the bottom) - > Update pane.

**Comment by DavidBrainard** [comment]
What is the “control panel”

DB

> On Apr 27, 2015, at 3:56 PM, Nicolas Cottaris notifications@github.com wrote:
> 
> After updating my Java Installation to Java 8 Update 45, this problem was eliminated.
> ControlPanel -> Java (all the way at the bottom) - > Update pane.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/DavidBrainard/BrainardLabToolbox/issues/1#issuecomment-96796842.

# 

David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by npcottaris** [comment]
Oopps. I meant to say System Preferences -> Java …

N.

**Comment by DavidBrainard** [comment]
There is no Java panel in my system preferences.  I’m running 10.10.2.  Should I be looking elsewhere?  Installing some update?

> On Apr 30, 2015, at 3:13 PM, Nicolas Cottaris notifications@github.com wrote:
> 
> Oopps. I meant to say System Preferences -> Java …
> 
> N.
> 
> > On Apr 30, 2015, at 3:11 PM, David Brainard notifications@github.com wrote:
> > 
> > What is the “control panel”
> > 
> > DB
> > 
> > > On Apr 27, 2015, at 3:56 PM, Nicolas Cottaris notifications@github.com wrote:
> > > 
> > > After updating my Java Installation to Java 8 Update 45, this problem was eliminated.
> > > ControlPanel -> Java (all the way at the bottom) - > Update pane.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub https://github.com/DavidBrainard/BrainardLabToolbox/issues/1#issuecomment-96796842.
> > 
> > # 
> > 
> > David H. Brainard
> > RRL Professor of Psychology
> > Director, Vision Research Center
> > Director, Institute for Research in Cognitive Science
> > University of Pennsylvania
> > 3401 Walnut Street, Suite 400A (mail address)
> > 3401 Walnut Street, Room 315C (office location)
> > Philadelphia, PA, 19104
> > Phone: 215-573-7579
> > Email: brainard@psych.upenn.edu
> > Web: http://color.psych.upenn.edu/brainard
> > 
> > —
> > Reply to this email directly or view it on GitHub https://github.com/DavidBrainard/BrainardLabToolbox/issues/1#issuecomment-97931600.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/DavidBrainard/BrainardLabToolbox/issues/1#issuecomment-97932525.

# 

David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by npcottaris** [comment]
Download from here:

http://java.com/en/download/mac_download.jsp?locale=en http://java.com/en/download/mac_download.jsp?locale=en

**Comment by DavidBrainard** [comment]
Closing this issue.
